= Songpark Teleporter version switcher

== Description

Songpark teleporter version switcher is a python script that automates the switching of the teleporter FPGA core and connect program.

== Setup

=== Requirements

* pipenv

=== Installation

1. Install the dependencies to the system by running `pipenv install --system`
2. Install the script itself by running `pip install -e .`

You should now be able to run the script anywhere by running `tp-version-switch`

== Filestructure of version files

----
/opt/songpark
└── versions_available
    ├── version1 (the name of this directory will be used in the list of choices)
    │   ├── connect
    │   │   └── connect
    │   ├── fpga
    │   │   ├── BOOT.bin
    │   │   ├── devicetree.dtb
    │   │   └── uImage
    │   └── hash.md5 (optional)
----

== How to make a hash.md5 file

1. Change into the directory of the version
2. run `md5sum connect/connect fpga/BOOT.bin fpga/uImage fpga/devicetree.dtb > hash.md5`

== Changing a version

1. Run `tp-version-switch`
2. Choose the version you want to switch to
3. Choose to reboot the system or not
